### ISSUE TITLE
Does this program works for macOS 10.14? How to uninstall this program?

### ISSUE THREAD

**Issue by bhishanpdl** [w0lfschild/moreMenu#6]
Date: Jan 5, 2019
macos: 10.14 mojave

I downloaded and installed mySIMBL and cleanMenu apps.
Also installed Afloat app.

But, when I restart terminal or Finder or any app, nothing happens.
I don't have iTerm, does it only work for iTerm or works for all the apps?

I have also allowed security preferences when it asked to give permissions.

Related images:
https://imgur.com/a/bLhhral

https://imgur.com/a/bBYXYJE

I am sorry, How to uninstall this app clearly?

When I deleted the app from the Applications folder, still when I open some apps, it asks SIML agents wants Access.

Is this app virus or something?
The error is persistent on MacOS 10.14.

**Comment by w0lfschild** [comment]
My guess is that maybe you had System Integrity Protection on.

Also no mySIMBL isn't a virus the warning was added in 10.14 and mySIMBL hasn't been updated for 10.14

You can try using [MacForge](https://github.com/w0lfschild/MacForge) instead.
